name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-grpc-micro
      
    - name: Run the Docker image
      run: docker run --expose 8080 go-grpc-micro
